### ISSUE TITLE
Clarification on  aggregated report batching and privacy budget exhaustion

### ISSUE THREAD

**Issue by rameetchandok** [privacysandbox/aggregation-service#52]
Hi aggregation service team, we(Adform) are facing issues Privacy budget Exhaustion issue due to duplicate reports. We are following the batching criteria
mentioned at 
https://github.com/privacysandbox/aggregation-service/blob/e555200fa1f88690f51cbf0b4c3af087d00bf5ae/java/com/google/aggregate/adtech/worker/aggregation/engine/AggregationEngine.java#L94

and 

https://github.com/privacysandbox/aggregation-service/blob/e555200fa1f88690f51cbf0b4c3af087d00bf5ae/java/com/google/aggregate/privacy/budgeting/AttributionReportingPrivacyBudgetKeyGenerator.java#L37

Based on the above rules, we tried to reverse engineer the batch data to check if we do have any duplicate reports across all our batch data but we couldn't find any .

We also looked at https://github.com/privacysandbox/aggregation-service/issues/35 and cross verified our assumption with the code as well.

Is there any other way we can have more debug information as to across which batches we have these duplicate reports with the same key.

Can you please provide any information on how to proceed with debugging this issue.

**Comment by maybellineboon** [comment]
Hi @rameetchandok ,

Privacy Budget exhaustion issue happens when you try to batch a report whose shared ID is has already been included in a previously successful batch.

When you collect the reports in a single batch, please try to ensure that all reports with the same shared ID are in the same batch. More guidance to this are shared in the [batching strategies doc](https://github.com/privacysandbox/aggregation-service/blob/main/docs/batching-strategies.md).

From [#35](https://github.com/privacysandbox/aggregation-service/issues/35#issuecomment-1874327993), shared ID is comprised of api version, reporting origin, destination site, source registration time (truncated by the day) and scheduled report time (truncated by the hour).

Would you be able to help confirm that all reports are batched according to the shared ID fields? Also, can you help confirm if you are separating the reports into batches that are received in production and debug endpoint?

**Comment by rameetchandok** [comment]
Hi yes all reports were batched according to shared ID fields. An important thing i missed to mention is that the reports fail if batched for 1 day, however when batched for 7 days, they paas.

**Comment by maybellineboon** [comment]
Hi @rameetchandok ,

All reports regardless of production or debug endpoint, will need to be batched according to shared ID. If you have a batch where the shared ID both exist in production and debug, you will encounter a privacy budget exhausted error.

For example, you process the debug endpoint batch first and a specific shared ID with the following information gets processed. Any reports in the production endpoint batch with the same shared ID (below information) will return with a privacy budget exhausted error because the budget for that shared ID has already been consumed by the previous batch.

__api:__ attribution-reporting
__attribution_destination:__ https://privacy-sandcastle-dev-shop.web.app
__reporting_origin:__ https://privacy-sandcastle-dev-dsp.web.app
__scheduled_report_time (hour):__ 1704214800
__source_registration_time (day):__ 0
__version:__ 0.1

**Comment by rameetchandok** [comment]
Hi, but we always process debug batches 1 hour after processing non-debug batches.

**Comment by maybellineboon** [comment]
Hi @rameetchandok ,

Would you be able to help share the reports you batched? both for the single batch of 7 days and the daily batches for 7 days? Please also include the getJob requests. If you can help put all reports for the same batch in a single folder (below folder structure), this will help us.

batches
 |--7 day batch
 |--daily batch
     |--day 1 batch
     |--day 2 batch
     |--day 3 batch
     |--day 4 batch
     |--day 5 batch
     |--day 6 batch
     |--day 7 batch

**Comment by rameetchandok** [comment]
Hi, apologies for the late reply, please find attached the requested batches.
[batches.zip](https://github.com/privacysandbox/aggregation-service/files/15344071/batches.zip)

**Comment by maybellineboon** [comment]
Hi @rameetchandok ,

I've downloaded your files. Would you be able to delete your comment since these files are your private files and this is visible publicly?

Also, it's better to discuss this in email.

**Comment by maybellineboon** [comment]
Have worked with @rameetchandok team offline and resolved this issue.
