### ISSUE TITLE
How to generate output_domain.avro when the values ​​that make up your bucket are dynamic (example: creative id)

### ISSUE THREAD

**Issue by dbrito** [privacysandbox/aggregation-service#58]
Hi guys, does anyone here have any strategy on how to generate the output_domain.avro when the values ​​that make up the bucket are dynamic (example: a creative id)? It's just that we are implementing attribution-reporting in our company and our report key is not fixed as we already use the ID of the creatives, this means that we cannot map the keys (the volume of creatives we have would be very large)

Example do código que thet define the value of the keys (bucket):
```js
const registerSource = (req, res) => {
    if (req.headers['attribution-reporting-eligible']) {
        let SOURCE_PARAMS = {
            source_event_id: Date.now().toString(), 
            destination: req.query.destination, 
            expiry: 2592000, 
            event_report_window: 3600, 
            priority: "0", 
            aggregation_keys: { // Defining the value of the keys (bucket)
                creativeId: Utils.toHex(req.query.creativeId), 
                lineItemId: Utils.toHex(req.query.lineItemId), 
                pixelId: Utils.toHex(0),
            },
            aggregatable_report_window: "86400", 
            filter_data: {
                creativeId: [`${req.query.creativeId}`], 
                lineItemId: [`${req.query.lineItemId}`] 
            },
            debug_key: "260893",
        }


        res.set('Attribution-Reporting-Register-Source', JSON.stringify(SOURCE_PARAMS));
        res.status(200).send('OK');
    } else {
        res.statusCode = 400;
        res.end('Invalid request');
    }
}
```

**Comment by Svenmay** [comment]
Hi @dbrito 

With ARA, you will be creating your source key (including your creativeId, lineItemId, pixelId) in your server to pass the Attribution-Reporting-Register-Source header. Once your server receives the source registration request which includes the creativeId, lineItemId, pixelId, etc, you should be able to create the source key pieces on your end and store them. The same source key pieces are passed on to the Attribution-Reporting-Register-Source header response.

Once you have your source key pieces, given that you know your trigger/conversion key piece, you can perform a bit-wise OR on the source and trigger key piece to get the final key-piece.

As an example (from the [explainer](https://github.com/WICG/attribution-reporting-api/blob/main/AGGREGATE.md)).

The source has 2 aggregation key (campaignCount 0x159 and geoValue 0x5) for this specific advertisement.

The adtech knows that:

campaignCount will have possible 3 conversion types: 1, 2, 3 (with a 9 bit offset since campaignCount can have 511 possible values)
geoValue will have possible 4 different categories per geo: 21, 25, 28, 30 (with a 7 bit offset since geo has ~100 possible values)
Then, the adtech will know that for the campaignCount 0x159 (that was stored when the source key was created), will have the following keys:

0x200 (for conversion type 1) | 0x159 = 0x659
0x400 (for conversion type 2) | 0x159 = 0x559
0x600 (for conversion type 3) | 0x159 = 0x759
The same way for geoValue where you have 0x5 that was stored when the source key was created. You will end up having the following keys:

0xa80 (for category 21) | 0x5 = 0xa85
0xc80 (for category 25) | 0x5 = 0xc85
0xe00 (for category 28) | 0x5 = 0xe05
0xf00 (for category 28) | 0x5 = 0xf05
So, in Aggregation Service when creating the output domain, the adtech will know that they do have source key pieces 0x159 and 0x5. But they will have to combine with the trigger key piece possible combinations. And will have the following keys in output domain:

0x659
0x559
0x759
0xa85
0xc85
0xe05
0xf05

I hope this clarifies this. If not, please let me know.

**Comment by dbrito** [comment]
Hi Svenmay,

I understood the part about how the key is composed, including below is the code that accounts for the conversion (it adds the "pixelId" that works if it were an Admanager activity), making our final key (bucket) composed of creativeId, lineItemId and pixelId

```js
const Utils = require('../utils/Utils.js')

const registerConversion = (req, res) => {
    console.log('Registrando Conversão');
    const triggerRegistrationData = JSON.stringify({
        event_trigger_data: [{
            trigger_data: req.query.pixelId
        }],
        aggregatable_trigger_data: [
            {
                key_piece: Utils.toHex(req.query.pixelId),
                source_keys: ["pixelId"],
            },
            {
                key_piece: Utils.toHex(0),
                source_keys: ["creativeId"],
            },
            {
                key_piece: Utils.toHex(0),
                source_keys: ["lineItemId"],
            },
        ],
        aggregatable_values: {
            creativeId: 10000,
            lineItemId: 10000,
            pixelId: 10000,
        },
        debug_key: '289279453067342',
        debug_reporting: true
    });

    res.set('Attribution-Reporting-Register-Trigger', triggerRegistrationData);
    
    res.status(200).send('OK');
}

module.exports = {
    registerConversion
};
```

What I didn't understand very well is whether there would be an alternative that didn't involve generating the output_domain.avro (which from what I understand needs to have all the possible values ​​of the key, which in our case would be composed of creativeId, lineItemId and pixelI) because in the In our case of being an adtech, the possibilities change all the time, as our clients are always creating new creatives, lineItems and conversion pixels

**Comment by maybellineboon** [comment]
Hi @dbrito ,

We do have a [key discovery](https://github.com/WICG/attribution-reporting-api/blob/main/aggregate_key_discovery.md) proposal where you will no longer need to work with pre-declared buckets. However, for key discovery, you will have to either have a key-mask or set thresholds for buckets exceeding specific thresholds to be included in the output. This is explained further in the shared explainer.

Seeing from your end where pixelId is it's own field and is not specified in the source registration and only in trigger passed through a link decorator, your server receiving the trigger registration request should be able to store this.

From your flow:
1) Receive "https://attribution.ads.uol.com.br/register-source?lineItemId=111&creativeId=666&destination=https://cliente.com/produto.html" as source registration request. Store lineItemId `111` as the key for linteItemId, store creativeId `666` as the key for creativeId (for output domain).
2) Conversion request "https://attribution.ads.uol.com.br/register-conversion?pixelId=444" to your server. Store pixelId `444` as the key for pixelId (for output domain).

3) On Aggregation Service batching, since you already know your corresponding lineItemId, creativeId and pixelId, you should be able to add all these in your output domain for batching request.

Let me know if I missed anything.

**Comment by dbrito** [comment]
Hello @maybellineboon 

Good news to know that this functionality may be available in the future.
It will definitely be something that will help a lot in making the process simpler and faster.

Thank you very much for the tip

**Comment by dbrito** [comment]
@maybellineboon First of all, I apologize for calling you again, but could you explain how you transform my keys into a "domain.avro"?

I saw in the [example](https://github.com/privacysandbox/aggregation-service/blob/main/docs/collecting.md#output_domainavsc) that "Avro Tools" is used in conjunction with a JSON file, but I was unable to make a relationship with what I have (which are the keys in hexadecimal format) with the json file examples in the document

If it was difficult to understand, I would summarize it as, how do I transform this

```json
[
 {
  "key": "0x29a", //creativeId 666
  "value": 10000 //1 conversion count * 10000 to reduce noise impact
 },
 {
  "key": "0x6f", //lineItemId 111
  "value": 10000 //1 conversion count * 10000 to reduce noise impact
 },
 {
  "key": "0x1bc", //pixelId 444
  "value": 10000 //1 conversion count * 10000 to reduce noise impact
 }
]
```

in this (one of the examples)

```json
{
    "bucket": "<øg\u0090?»sì&Õ\u0018À\u0096\u008c)Ü"
}
```
or this (one of the examples)

```json
{
    "bucket": "\u003c\u00f8\u0067\u0090\u003f\u00bb\u0073\u00ec\u0026\u00d5\u0018\u00c0\u0096\u008c\u0029\u00dc"
}
```

**Comment by maybellineboon** [comment]
Hi @dbrito ,

Not a problem.

To create a domain avro, you will need to use the [domain schema](https://github.com/privacysandbox/aggregation-service/blob/main/docs/collecting.md#output_domainavsc). The bucket key will have to be converted into hexadecimal format and converted into a bytestring. For your example, you will have to convert `0x29a` into a bytestring. So for this example, your bucket in JSON format is:
```
{
    "bucket":"\u0002\u009a"
}
```
We do have a [sample tool](https://github.com/privacysandbox/privacy-sandbox-demos/tree/main/tools/aggregatable_report_converter) to help you generate the domain avro from a decimal format.

**Comment by dbrito** [comment]
Hi @maybellineboon, firstly sorry for the delay 

I would like to inform you that with your help I managed to do it! Now our attribution-reporting can go through the entire flow (from interacting with the creative to creating the summary report), we are still having some difficulties with noise but that is another matter

I would like to thank you once again, from the moment I knew that the format should be a byteString everything else became much easier

I also leave here the code I used to transform my keys into a byteString

```js
function hexToBytestring(hexString) {
    hexString = hexString.replace('0x', '0');
    let bytestring = '';
    for (let i = 0; i < hexString.length; i += 2) {
        let hexPair = hexString.substring(i, i + 2);
        let charCode = parseInt(hexPair, 16);
        bytestring += String.fromCharCode(charCode);
    }
    return bytestring;
}

function bytestringToHex(bytestring) {
    let hexString = '';
    for (let i = 0; i < bytestring.length; i++) {
        let hex = bytestring.charCodeAt(i).toString(16).padStart(2, '0');
        hexString += hex;
    }
    return hexString;
}

```

Thank you !
